# Generated by Django 4.2.17 on 2025-10-15 18:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe ser de más de dos caracteres')], verbose_name='Nombre')),
                ('order', models.IntegerField(default=0, verbose_name='Orden personalizado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe ser de más de dos caracteres')], verbose_name='Título')),
                ('ingredients', models.JSONField(blank=True, default=list, verbose_name='Ingredientes')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Cuerpo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category', verbose_name='Categoría')),
                ('related_recipes', models.ManyToManyField(blank=True, related_name='referenced_by', to='recipes.recipe', verbose_name='Recetas relacionadas')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['title'],
            },
        ),
    ]
