# Generated by Django 4.2.17 on 2026-05-03 06:15

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_jsonform.models.fields.JSONField(blank=True, verbose_name='Ingredientes'),
        ),
    ]
