# Generated by Django 4.2.17 on 2024-12-24 17:26

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_name_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
