# Generated by Django 4.2.17 on 2026-05-03 06:49

from django.db import migrations
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_jsonform.models.fields.JSONField(blank=True, default=None, null=True, verbose_name='Ingredientes'),
        ),
    ]
