# Generated by Django 4.2.17 on 2025-10-21 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredient_second_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='main_quantity',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
