# Generated by Django 4.2.17 on 2025-01-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_related_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='related_recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='related_recipes',
            field=models.ManyToManyField(blank=True, related_name='referenced_by', to='recipes.recipe'),
        ),
    ]
