# Generated by Django 4.2.17 on 2025-01-07 03:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_related_recipes_recipe_related_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe ser de más de dos caracteres')], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Orden personalizado'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Cuerpo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None, verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='related_recipes',
            field=models.ManyToManyField(blank=True, related_name='referenced_by', to='recipes.recipe', verbose_name='Recetas relacionadas'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'El nombre debe ser de más de dos caracteres')], verbose_name='Título'),
        ),
    ]
