# Generated by Django 4.2.17 on 2025-10-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_category_name_alter_category_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title'], 'verbose_name': 'Receta', 'verbose_name_plural': 'Recetas'},
        ),
    ]
